// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/handshake.proto

package secpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cipher suite identifiers negotiated during handshake.
type CipherSuite int32

const (
	CipherSuite_CIPHER_SUITE_UNSPECIFIED       CipherSuite = 0
	CipherSuite_CIPHER_SUITE_AES_256_GCM       CipherSuite = 1
	CipherSuite_CIPHER_SUITE_CHACHA20_POLY1305 CipherSuite = 2
)

// Enum value maps for CipherSuite.
var (
	CipherSuite_name = map[int32]string{
		0: "CIPHER_SUITE_UNSPECIFIED",
		1: "CIPHER_SUITE_AES_256_GCM",
		2: "CIPHER_SUITE_CHACHA20_POLY1305",
	}
	CipherSuite_value = map[string]int32{
		"CIPHER_SUITE_UNSPECIFIED":       0,
		"CIPHER_SUITE_AES_256_GCM":       1,
		"CIPHER_SUITE_CHACHA20_POLY1305": 2,
	}
)

func (x CipherSuite) Enum() *CipherSuite {
	p := new(CipherSuite)
	*p = x
	return p
}

func (x CipherSuite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CipherSuite) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_handshake_proto_enumTypes[0].Descriptor()
}

func (CipherSuite) Type() protoreflect.EnumType {
	return &file_proto_handshake_proto_enumTypes[0]
}

func (x CipherSuite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CipherSuite.Descriptor instead.
func (CipherSuite) EnumDescriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{0}
}

// Client -> Server (plaintext). Initiates the handshake.
type ClientHello struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Version               uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CipherSuites          []CipherSuite          `protobuf:"varint,2,rep,packed,name=cipher_suites,json=cipherSuites,proto3,enum=secproto.v1.CipherSuite" json:"cipher_suites,omitempty"`
	ClientRandom          []byte                 `protobuf:"bytes,3,opt,name=client_random,json=clientRandom,proto3" json:"client_random,omitempty"`                              // 32 bytes high-entropy
	ClientEphemeralPubkey []byte                 `protobuf:"bytes,4,opt,name=client_ephemeral_pubkey,json=clientEphemeralPubkey,proto3" json:"client_ephemeral_pubkey,omitempty"` // 32 bytes X25519
	ClientIdentityPubkey  []byte                 `protobuf:"bytes,5,opt,name=client_identity_pubkey,json=clientIdentityPubkey,proto3" json:"client_identity_pubkey,omitempty"`    // 32 bytes Ed25519 (long-term identity)
	AuthToken             []byte                 `protobuf:"bytes,6,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`                                       // optional PSK/token
	ClientTime            int64                  `protobuf:"varint,7,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`                                   // Unix nanoseconds, for clock offset estimation
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientHello) GetCipherSuites() []CipherSuite {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *ClientHello) GetClientRandom() []byte {
	if x != nil {
		return x.ClientRandom
	}
	return nil
}

func (x *ClientHello) GetClientEphemeralPubkey() []byte {
	if x != nil {
		return x.ClientEphemeralPubkey
	}
	return nil
}

func (x *ClientHello) GetClientIdentityPubkey() []byte {
	if x != nil {
		return x.ClientIdentityPubkey
	}
	return nil
}

func (x *ClientHello) GetAuthToken() []byte {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

func (x *ClientHello) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// Server -> Client (plaintext). Server's ephemeral key and selected suite.
type ServerHello struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Version               uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CipherSuite           CipherSuite            `protobuf:"varint,2,opt,name=cipher_suite,json=cipherSuite,proto3,enum=secproto.v1.CipherSuite" json:"cipher_suite,omitempty"`
	ServerRandom          []byte                 `protobuf:"bytes,3,opt,name=server_random,json=serverRandom,proto3" json:"server_random,omitempty"`                              // 32 bytes high-entropy
	ServerEphemeralPubkey []byte                 `protobuf:"bytes,4,opt,name=server_ephemeral_pubkey,json=serverEphemeralPubkey,proto3" json:"server_ephemeral_pubkey,omitempty"` // 32 bytes X25519
	ServerIdentityPubkey  []byte                 `protobuf:"bytes,5,opt,name=server_identity_pubkey,json=serverIdentityPubkey,proto3" json:"server_identity_pubkey,omitempty"`    // 32 bytes Ed25519
	ServerTime            int64                  `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`                                   // Unix nanoseconds, for clock offset estimation
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerHello) GetCipherSuite() CipherSuite {
	if x != nil {
		return x.CipherSuite
	}
	return CipherSuite_CIPHER_SUITE_UNSPECIFIED
}

func (x *ServerHello) GetServerRandom() []byte {
	if x != nil {
		return x.ServerRandom
	}
	return nil
}

func (x *ServerHello) GetServerEphemeralPubkey() []byte {
	if x != nil {
		return x.ServerEphemeralPubkey
	}
	return nil
}

func (x *ServerHello) GetServerIdentityPubkey() []byte {
	if x != nil {
		return x.ServerIdentityPubkey
	}
	return nil
}

func (x *ServerHello) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// Server -> Client (plaintext). Signature binds the handshake transcript.
type ServerProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 over transcript of ClientHello || ServerHello
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerProof) Reset() {
	*x = ServerProof{}
	mi := &file_proto_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerProof) ProtoMessage() {}

func (x *ServerProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerProof.ProtoReflect.Descriptor instead.
func (*ServerProof) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *ServerProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Client -> Server (encrypted). Proves client identity and binds transcript.
type ClientFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 over transcript of ClientHello || ServerHello || ServerProof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFinished) Reset() {
	*x = ClientFinished{}
	mi := &file_proto_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFinished) ProtoMessage() {}

func (x *ClientFinished) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFinished.ProtoReflect.Descriptor instead.
func (*ClientFinished) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *ClientFinished) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Server -> Client (encrypted). Final confirmation.
type ServerFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFinished) Reset() {
	*x = ServerFinished{}
	mi := &file_proto_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFinished) ProtoMessage() {}

func (x *ServerFinished) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFinished.ProtoReflect.Descriptor instead.
func (*ServerFinished) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *ServerFinished) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Either direction (encrypted). Triggers key rotation.
type Rekey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NewKeyId           uint32                 `protobuf:"varint,1,opt,name=new_key_id,json=newKeyId,proto3" json:"new_key_id,omitempty"`
	NewEphemeralPubkey []byte                 `protobuf:"bytes,2,opt,name=new_ephemeral_pubkey,json=newEphemeralPubkey,proto3" json:"new_ephemeral_pubkey,omitempty"` // 32 bytes X25519
	NewRandom          []byte                 `protobuf:"bytes,3,opt,name=new_random,json=newRandom,proto3" json:"new_random,omitempty"`                              // 32 bytes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Rekey) Reset() {
	*x = Rekey{}
	mi := &file_proto_handshake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rekey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rekey) ProtoMessage() {}

func (x *Rekey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rekey.ProtoReflect.Descriptor instead.
func (*Rekey) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{5}
}

func (x *Rekey) GetNewKeyId() uint32 {
	if x != nil {
		return x.NewKeyId
	}
	return 0
}

func (x *Rekey) GetNewEphemeralPubkey() []byte {
	if x != nil {
		return x.NewEphemeralPubkey
	}
	return nil
}

func (x *Rekey) GetNewRandom() []byte {
	if x != nil {
		return x.NewRandom
	}
	return nil
}

// Either direction (encrypted). Application payload.
type AppData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppData) Reset() {
	*x = AppData{}
	mi := &file_proto_handshake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppData) ProtoMessage() {}

func (x *AppData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppData.ProtoReflect.Descriptor instead.
func (*AppData) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{6}
}

func (x *AppData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_handshake_proto protoreflect.FileDescriptor

const file_proto_handshake_proto_rawDesc = "" +
	"\n" +
	"\x15proto/handshake.proto\x12\vsecproto.v1\"\xb9\x02\n" +
	"\vClientHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12=\n" +
	"\rcipher_suites\x18\x02 \x03(\x0e2\x18.secproto.v1.CipherSuiteR\fcipherSuites\x12#\n" +
	"\rclient_random\x18\x03 \x01(\fR\fclientRandom\x126\n" +
	"\x17client_ephemeral_pubkey\x18\x04 \x01(\fR\x15clientEphemeralPubkey\x124\n" +
	"\x16client_identity_pubkey\x18\x05 \x01(\fR\x14clientIdentityPubkey\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x06 \x01(\fR\tauthToken\x12\x1f\n" +
	"\vclient_time\x18\a \x01(\x03R\n" +
	"clientTime\"\x98\x02\n" +
	"\vServerHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12;\n" +
	"\fcipher_suite\x18\x02 \x01(\x0e2\x18.secproto.v1.CipherSuiteR\vcipherSuite\x12#\n" +
	"\rserver_random\x18\x03 \x01(\fR\fserverRandom\x126\n" +
	"\x17server_ephemeral_pubkey\x18\x04 \x01(\fR\x15serverEphemeralPubkey\x124\n" +
	"\x16server_identity_pubkey\x18\x05 \x01(\fR\x14serverIdentityPubkey\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\x03R\n" +
	"serverTime\"+\n" +
	"\vServerProof\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\".\n" +
	"\x0eClientFinished\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"*\n" +
	"\x0eServerFinished\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"v\n" +
	"\x05Rekey\x12\x1c\n" +
	"\n" +
	"new_key_id\x18\x01 \x01(\rR\bnewKeyId\x120\n" +
	"\x14new_ephemeral_pubkey\x18\x02 \x01(\fR\x12newEphemeralPubkey\x12\x1d\n" +
	"\n" +
	"new_random\x18\x03 \x01(\fR\tnewRandom\"\x1d\n" +
	"\aAppData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*m\n" +
	"\vCipherSuite\x12\x1c\n" +
	"\x18CIPHER_SUITE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CIPHER_SUITE_AES_256_GCM\x10\x01\x12\"\n" +
	"\x1eCIPHER_SUITE_CHACHA20_POLY1305\x10\x02BHZFgithub.com/Echoed-Abyss/TCP-Protobuf-Server/internal/proto/secpb;secpbb\x06proto3"

var (
	file_proto_handshake_proto_rawDescOnce sync.Once
	file_proto_handshake_proto_rawDescData []byte
)

func file_proto_handshake_proto_rawDescGZIP() []byte {
	file_proto_handshake_proto_rawDescOnce.Do(func() {
		file_proto_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_handshake_proto_rawDesc), len(file_proto_handshake_proto_rawDesc)))
	})
	return file_proto_handshake_proto_rawDescData
}

var file_proto_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_handshake_proto_goTypes = []any{
	(CipherSuite)(0),       // 0: secproto.v1.CipherSuite
	(*ClientHello)(nil),    // 1: secproto.v1.ClientHello
	(*ServerHello)(nil),    // 2: secproto.v1.ServerHello
	(*ServerProof)(nil),    // 3: secproto.v1.ServerProof
	(*ClientFinished)(nil), // 4: secproto.v1.ClientFinished
	(*ServerFinished)(nil), // 5: secproto.v1.ServerFinished
	(*Rekey)(nil),          // 6: secproto.v1.Rekey
	(*AppData)(nil),        // 7: secproto.v1.AppData
}
var file_proto_handshake_proto_depIdxs = []int32{
	0, // 0: secproto.v1.ClientHello.cipher_suites:type_name -> secproto.v1.CipherSuite
	0, // 1: secproto.v1.ServerHello.cipher_suite:type_name -> secproto.v1.CipherSuite
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_handshake_proto_init() }
func file_proto_handshake_proto_init() {
	if File_proto_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_handshake_proto_rawDesc), len(file_proto_handshake_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_handshake_proto_goTypes,
		DependencyIndexes: file_proto_handshake_proto_depIdxs,
		EnumInfos:         file_proto_handshake_proto_enumTypes,
		MessageInfos:      file_proto_handshake_proto_msgTypes,
	}.Build()
	File_proto_handshake_proto = out.File
	file_proto_handshake_proto_goTypes = nil
	file_proto_handshake_proto_depIdxs = nil
}
